version: '3'

services:
  postgres:
    image: postgres:13.1
    container_name: contreaul-db
    restart: always
    networks:
      - contreaul-net
    environment:
      - POSTGRES_USER=contreaul
      - POSTGRES_PASSWORD=contreaul
      - APP_DB_USER=contreaul
      - APP_DB_PASS=contreaul
      - APP_DB_NAME=contreaul-db
    volumes:
      - postgres-db:/docker-entrypoint-initdb.d/
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
  cloudbeaver:
      image: dbeaver/cloudbeaver:21.3.3
      container_name: cloudbeaver
      restart: always
      networks:
       - contreaul-net
      ports:
       - 8978:8978
      volumes:
       - cloudbeaver:/opt/cloudbeaver/workspace

networks:
  contreaul-net:

volumes:
  postgres-db:
    driver: local
  cloudbeaver:
    driver: local
