version: '3'

services:
  postgres:
    image: postgres:13.1
    container_name: contreaul-db
    restart: always
    environment:
      - POSTGRES_USER=contreaul
      - POSTGRES_PASSWORD=contreaul
      - APP_DB_USER=contreaul
      - APP_DB_PASS=contreaul
      - APP_DB_NAME=contreaul-db
    volumes:
      - postgres-db:/docker-entrypoint-initdb.d/
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
  cloudbeaver:
      image: dbeaver/cloudbeaver:21.3.3
      container_name: cloudbeaver
      restart: always
      ports:
       - APP_HTTP_PORT=8978
      volumes: 
       - cloudbeaver:/opt/cloudbeaver/workspace            

networks:
  default:
    name: contreaul-net
    external: true

volumes:
  postgres-db:
    driver: local